
[package]
name = "fluisim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
bevy_egui = "0.33.0"
itertools = "0.14.0"

hydrodynamics = { version = "0.1.0", path = "../hydrodynamics" }
util = { version = "0.1.0", path = "../util" }
